name: openssh node execution services
rundeckPluginVersion: 1.0
author: Alex Honor
date: 08/14/2015
version: 1.0
providers:
    - name: ssh-exec
      service: NodeExecutor
      title: openssh-exec
      description: Executes the command on the node.
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: ssh-exec.sh
      script-args: ${node.username} ${node.hostname} ${exec.command}
      config:
        - name: ssh_key_storage_path
          title: SSH key Storage Path
          type: String
          required: false
          description: "Optional storage path for ssh-key file. Can contain property references to node attributes. A node attribute named ssh-key-storage-path will override this value."
          scope: Instance
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
            instance-scope-node-attribute: "ssh-key-storage-path"
    - name: ssh-copier
      service: FileCopier
      title: openssh-copier
      description: Copies file to the node via scp
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: ssh-copy.sh
      script-args: ${node.username} ${node.hostname} ${file-copy.file}
      config:
        - name: ssh_key_storage_path
          title: SSH key Storage Path
          type: String
          required: false
          description: "Optional storage path for ssh-key file. Can contain property references to node attributes. A node attribute named ssh-key-storage-path will override this value."
          scope: Instance
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
            instance-scope-node-attribute: "ssh-key-storage-path"
